plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
title: Développeuse web, SEO et Community manager
description: Bienvenue sur mon cv en ligne. Après 10 ans dans le webmarketing, je me reconvertis dans le développement web. Je recherche actuellement une alternance d'un an dans les environs de Valence (Drôme).
url: https://www.sarah-hans.com
author: Sarah hans
logo:
twitter:
  username: lageekette